#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
// 关闭错误显示
ini_set('display_errors', 0);
// 开启错误显示
// error_reporting(E_ALL);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
// 加载自动加载文件

// 加载自动加载文件
require __DIR__ . '/vendor/autoload.php';
// 加载Yii框架
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
// 加载配置文件
$config = require __DIR__ . '/config/console.php';

// 创建应用实例
$application = new yii\console\Application($config);
// 运行应用
$exitCode = $application->run();
exit($exitCode);
